-- 查看某个ORACLE相关进程正在执行的SQL
SELECT SQL_TEXT, SPID, V$SESSION.PROGRAM, PROCESS
  FROM V$SQLAREA, V$SESSION, V$PROCESS
 WHERE V$SQLAREA.ADDRESS = V$SESSION.SQL_ADDRESS 
   AND V$SQLAREA.HASH_VALUE = V$SESSION.SQL_HASH_VALUE     
   AND V$SESSION.PADDR = V$PROCESS.ADDR     
   AND V$PROCESS.SPID IN (&PID); -- 进程号
