SELECT SQL_ID,
       PLAN_HASH_VALUE PLAN,
       TO_CHAR(BEGIN_INTERVAL_TIME, 'yyyymmdd') RUNDATE,
       SUM(EXECUTIONS_DELTA) AS EXEC, -- 执行次数（增量）
       TO_CHAR(MIN(BEGIN_INTERVAL_TIME), 'hh24mi') START_TIME, -- 开始时间
       TO_CHAR(MAX(END_INTERVAL_TIME), 'hh24mi') END_TIME, -- 结束时间
       SUM(BUFFER_GETS_DELTA) AS BUFFER, -- buffer get（增量）
       SUM(PHYSICAL_READ_BYTES_DELTA) AS PHY_READ,  -- 物理读（增量）
       ROUND(SUM(CPU_TIME_DELTA) / 1000000) "cpu(s)",  -- CPU时间（增量）
       ROUND(SUM(ELAPSED_TIME_DELTA) / 1000000) "elp(s)", -- 耗费时间（增量）
       SUM(DISK_READS_DELTA) READ, -- 磁盘读（增量）
       SUM(IOWAIT_DELTA) IOWAIT, -- IO等待（增量）
       SUM(DIRECT_WRITES_DELTA) DIRECT, -- 直接路径写（增量）
       SUM(BUFFER_GETS_DELTA) / SUM(EXECUTIONS_DELTA) BUFFER_PER_EXEC -- 平均每次执行buffer get大小
  FROM DBA_HIST_SQLSTAT ST, DBA_HIST_SNAPSHOT SN
 WHERE ST.SNAP_ID = SN.SNAP_ID
   AND ST.INSTANCE_NUMBER = SN.INSTANCE_NUMBER
   AND BEGIN_INTERVAL_TIME > SYSDATE - 60
   -- AND SQL_ID = '&sql_id'
 GROUP BY SQL_ID, PLAN_HASH_VALUE, TO_CHAR(BEGIN_INTERVAL_TIME, 'yyyymmdd')
 ORDER BY TO_CHAR(MIN(BEGIN_INTERVAL_TIME), 'YYYYMMDD-hh24mi')


SELECT ST.SQL_ID,
       ST.PLAN_HASH_VALUE PLAN, AR.SQL_TEXT,
       TO_CHAR(BEGIN_INTERVAL_TIME, 'yyyymmdd') RUNDATE,
       SUM(EXECUTIONS_DELTA) AS EXEC, -- 执行次数（增量）
       TO_CHAR(MIN(BEGIN_INTERVAL_TIME), 'hh24mi') START_TIME, -- 开始时间
       TO_CHAR(MAX(END_INTERVAL_TIME), 'hh24mi') END_TIME, -- 结束时间
       SUM(BUFFER_GETS_DELTA) AS BUFFER, -- BUFFER GET（增量）
       SUM(PHYSICAL_READ_BYTES_DELTA) AS PHY_READ,  -- 物理读（增量）
       ROUND(SUM(CPU_TIME_DELTA) / 1000000) "cpu(s)",  -- CPU时间（增量）
       ROUND(SUM(ELAPSED_TIME_DELTA) / 1000000) "elp(s)", -- 耗费时间（增量）
       SUM(DISK_READS_DELTA) READ, -- 磁盘读（增量）
       SUM(IOWAIT_DELTA) IOWAIT, -- IO等待（增量）
       SUM(DIRECT_WRITES_DELTA) DIRECT, -- 直接路径写（增量）
       DECODE(SUM(EXECUTIONS_DELTA), 0, 0, SUM(BUFFER_GETS_DELTA) / SUM(EXECUTIONS_DELTA)) BUFFER_PER_EXEC, -- 平均每次执行BUFFER GET大小
			 DECODE(SUM(EXECUTIONS_DELTA), 0, 0, SUM(PHYSICAL_READ_BYTES_DELTA) / SUM(EXECUTIONS_DELTA)) PHY_READ_PER, -- 平均每次执行物理读大小
			 DECODE(SUM(EXECUTIONS_DELTA), 0, 0, SUM(DISK_READS_DELTA) / SUM(EXECUTIONS_DELTA)) DISK_READ_PER -- -- 平均每次执行磁盘读大小
  FROM DBA_HIST_SQLSTAT ST, DBA_HIST_SNAPSHOT SN, V$SQLAREA AR
 WHERE ST.SNAP_ID = SN.SNAP_ID
   AND ST.INSTANCE_NUMBER = SN.INSTANCE_NUMBER
   AND BEGIN_INTERVAL_TIME > SYSDATE - 1
	 AND AR.SQL_ID = ST.SQL_ID
   -- AND AR.SQL_ID = '&sql_id'
 GROUP BY ST.SQL_ID, ST.PLAN_HASH_VALUE, TO_CHAR(BEGIN_INTERVAL_TIME, 'yyyymmdd'), AR.SQL_TEXT
 ORDER BY DECODE(SUM(EXECUTIONS_DELTA), 0, 0, SUM(PHYSICAL_READ_BYTES_DELTA) / SUM(EXECUTIONS_DELTA)) DESC,
 DECODE(SUM(EXECUTIONS_DELTA), 0, 0, SUM(DISK_READS_DELTA) / SUM(EXECUTIONS_DELTA)) DESC